// Generated by CoffeeScript 1.3.3
(function() {
  var centerOnItem, events;

  $(function() {
    return events();
  });

  events = function() {
    return $(".grid").click(function() {
      $(".active").removeClass("active");
      $(this).addClass("active");
      return centerOnItem(this);
    });
  };

  centerOnItem = function(el) {
    var centerX, centerY, height, item, position, width;
    item = $(el);
    position = item.position();
    width = item.width();
    height = item.height();
    centerX = Math.round(position.left + width / 2);
    centerY = Math.round(position.top + height / 2);
    return $("#field").transform("translate(" + (centerX * -1) + "px, " + (centerY * -1) + "px)");
  };

}).call(this);
