// Generated by CoffeeScript 1.3.3
(function() {
  var centerOnItem, events;

  $(function() {
    return events();
  });

  events = function() {
    return $(".grid").click(function() {
      $(".active").removeClass("active");
      $(this).addClass("active");
      return centerOnItem(this);
    });
  };

  centerOnItem = function(el) {
    var centerX, centerY, fieldX, fieldY, height, item, position, width;
    item = $(el);
    position = item.position();
    width = item.width();
    height = item.height();
    centerX = Math.round(position.left + width / 2);
    centerY = Math.round(position.top + height / 2);
    fieldX = centerX - $("#wrapper").width() / 2;
    fieldY = centerY - $("#wrapper").height() / 2;
    return $("#field").transform("translate(" + (fieldX * -1) + "px, " + (fieldY * -1) + "px)");
  };

}).call(this);
