// Generated by CoffeeScript 1.3.3
(function() {
  var attachEvents, centerOnItem, getTransitionTime, setTransformOrigin, transitionTime;

  transitionTime = 0;

  $(function() {
    getTransitionTime();
    attachEvents();
    return setTransformOrigin();
  });

  getTransitionTime = function() {
    transitionTime = $("#field").css("transition").split(" ")[1];
    return transitionTime = transitionTime.match(/ms$/) ? parseInt(trantisionTime.replace(/ms$/, ""), 10) : parseFloat(transitionTime.replace(/s$/, ""), 10) * 1000;
  };

  attachEvents = function() {
    return $(".grid").click(function() {
      $(".active").removeClass("active");
      $(this).addClass("active");
      return centerOnItem(this);
    });
  };

  setTransformOrigin = function() {
    return $("#zoom-wrapper").transformOrigin("" + ($("#wrapper").width() / 2) + "px " + ($("#wrapper").height() / 2) + "px");
  };

  centerOnItem = function(el) {
    var centerX, centerY, fieldX, fieldY, height, item, position, translateString, width,
      _this = this;
    item = $(el);
    position = item.position();
    width = item.width();
    height = item.height();
    centerX = Math.round(position.left + width / 2);
    centerY = Math.round(position.top + height / 2);
    fieldX = centerX - $("#wrapper").width() / 2;
    fieldY = centerY - $("#wrapper").height() / 2;
    translateString = "translate(" + (fieldX * -1) + "px, " + (fieldY * -1) + "px)";
    $("#zoom-wrapper").addClass("zoomed-out");
    $("#field").transform("" + translateString);
    return setTimeout(function() {
      return $("#zoom-wrapper").removeClass("zoomed-out");
    }, transitionTime / 2);
  };

}).call(this);
