// Generated by CoffeeScript 1.3.3
(function() {
  var backHome, duration, homeLinks, sizeHome;

  duration = 1000;

  $(function() {
    sizeHome();
    homeLinks();
    return backHome();
  });

  sizeHome = function() {
    $("#home").outerWidth($(window).width());
    return $("#home").outerHeight($(window).height());
  };

  homeLinks = function() {
    return $("body").on("click", "#home ul a", function(e) {
      var home_center_x, home_center_y;
      e.preventDefault();
      $("#home .return-home").show();
      home_center_x = ($("#stage").width() - $("#home").outerWidth()) / 2 * -1;
      home_center_y = ($("#stage").height() - $("#home").outerHeight()) / 2 * -1;
      home_center_x = "" + (home_center_x / 2) + "px";
      home_center_y = "" + (home_center_y / 2) + "px";
      console.log(home_center_y);
      console.log(home_center_x);
      return $("#stage").addClass("zoomed-out");
    });
  };

  backHome = function() {
    return $("body").on("click", ".return-home", function(e) {
      $("#home .return-home").hide();
      return $("#stage").removeClass("zoomed-out");
    });
  };

  jQuery.fn.transformOrigin = function(x, y) {
    return $(this).css({
      "-webkit-transform-origin": "" + x + " " + y,
      "-moz-transform-origin": "" + x + " " + y,
      "-ms-transform-origin": "" + x + " " + y,
      "-o-transform-origin": "" + x + " " + y,
      "transform-origin": "" + x + " " + y
    });
  };

}).call(this);
